service: cart-service

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true
provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'